# Generated by Django 6.0.7 on 2026-07-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_created=True)),
                ('orderId', models.IntegerField()),
                ('Item', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='dinning_table',
            name='orderID',
            field=models.IntegerField(default=0),
        ),
    ]
