# Generated by Django 6.0.7 on 2026-07-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_track_dinning_table_orderid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dinning_table',
            old_name='orderID',
            new_name='orderno',
        ),
        migrations.AlterField(
            model_name='dinning_table',
            name='table_number',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
