# Generated by Django 6.0.7 on 2026-07-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_orderid_dinning_table_orderno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinning_table',
            name='table_number',
            field=models.IntegerField(unique=True),
        ),
    ]
