# Generated by Django 6.0.7 on 2026-07-28 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_dinning_table_table_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dinning_table',
            name='orderno',
        ),
    ]
